version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=java-bd
    ports:
      - '5433:5432'
    volumes:
    - ./datosbd/:/docker-entrypoint-initdb.d/

  java-bd:
    container_name: java_bd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/java-bd
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: app_front
    ports:
      - 5173:5173
    volumes:
      - ./client:/home/test_java/client
      - /home/test_java/client/node_modules
    command: npm run dev
    tty: true
    restart: always
    environment:
      VITE_CONFIG: /home/test_java/client/vite.config.js


