INSERT INTO USUARIOS (NOMBRE_COMPLETO, CONTRASENIA, EMAIL, ESTADO, ROL)
VALUES ('Juan Alberto', 'admin', 'admin@gmail.com', 'ACTIVO', 'ADMIN');

INSERT INTO USUARIOS (NOMBRE_COMPLETO, CONTRASENIA, EMAIL, ESTADO, ROL)
VALUES ('Juana del Rio', 'admin', 'inactivo@gmail.com', 'INACTIVO', 'CONSULTOR');

INSERT INTO USUARIOS (NOMBRE_COMPLETO, CONTRASENIA, EMAIL, ESTADO, ROL)
VALUES ('Mike Britos', 'admin', 'consultor@gmail.com', 'ACTIVO', 'CONSULTOR');
