CREATE TABLE USUARIOS (
  USUARIO_ID BIGSERIAL PRIMARY KEY,
  NOMBRE_COMPLETO VARCHAR(50) NOT NULL,
  CONTRASENIA VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  ESTADO VARCHAR(100) NOT NULL,
  ROL VARCHAR(50) NOT NULL
);

CREATE INDEX IDX_USUARIOS_ESTADO ON USUARIOS(estado);


