CREATE TABLE USUARIOS (
  USUARIO_ID BIGSERIAL PRIMARY KEY,
  NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
  CONTRASENIA VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ESTADO VARCHAR(10) NOT NULL,
  ROL VARCHAR(10) NOT NULL
);

CREATE INDEX IDX_USUARIOS_ESTADO ON USUARIOS(estado);
ALTER TABLE USUARIOS ADD CONSTRAINT CHK_USUARIO_ACTIVO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));
ALTER TABLE USUARIOS ADD CONSTRAINT CHK_USUARIO_ROL CHECK (ROL IN ('ADMIN', 'CONSULTOR'));


