CREATE TABLE USUARIOS (
  USUARIO_ID BIGSERIAL PRIMARY KEY,
  NOMBRE_COMPLETO VARCHAR(50) NOT NULL,
  CONTRASENIA VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  ESTADO TINYINT(1) NOT NULL,
  ROL VARCHAR(50) NOT NULL
);

CREATE INDEX IDX_USUARIOS_ESTADO ON USUARIOS(estado);
ALTER TABLE USUARIOS ADD CONSTRAINT CHK_USUARIO_ROL CHECK (ROL IN ('ADMIN', 'CONSULTOR'));


